export const TRIGGER_COLORS = {
  "T-01": "#3b82f6", "T-02": "#06b6d4", "T-03": "#6b7280",
  "T-04": "#f59e0b", "T-05": "#ef4444", "T-06": "#8b5cf6", "T-07": "#f97316"
};

export const S = {
  app: {
    background: "#0a0a0f",
    minHeight: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    fontFamily: "'DM Sans', 'Inter', system-ui, sans-serif",
  },
  phoneFrame: {
    width: "390px",
    minHeight: "844px",
    background: "#0d0d14",
    position: "relative",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  screen: {
    flex: 1,
    overflowY: "auto",
    overflowX: "hidden",
    paddingBottom: "80px",
    scrollbarWidth: "none",
    padding: "0 0 80px 0",
  },
  card: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.07)",
    borderRadius: "16px",
    padding: "16px",
    marginBottom: "12px",
  },
  input: {
    width: "100%",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "12px",
    padding: "14px 16px",
    color: "#fff",
    fontSize: "15px",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
    marginBottom: "4px",
  },
  btn: (variant = "primary", disabled = false) => ({
    width: "100%",
    padding: "15px",
    borderRadius: "14px",
    border: "none",
    fontSize: "15px",
    fontWeight: "600",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.5 : 1,
    letterSpacing: "0.3px",
    transition: "all 0.2s",
    fontFamily: "inherit",
    ...(variant === "primary" ? {
      background: "linear-gradient(135deg, #4ade80, #22c55e)",
      color: "#0a1a0f",
    } : variant === "secondary" ? {
      background: "rgba(255,255,255,0.06)",
      border: "1px solid rgba(255,255,255,0.1)",
      color: "#fff",
    } : variant === "ghost" ? {
      background: "transparent",
      border: "1px solid rgba(255,255,255,0.15)",
      color: "rgba(255,255,255,0.7)",
    } : variant === "danger" ? {
      background: "rgba(239,68,68,0.12)",
      border: "1px solid rgba(239,68,68,0.25)",
      color: "#f87171",
    } : {
      background: "linear-gradient(135deg, #a855f7, #7c3aed)",
      color: "#fff",
    }),
  }),
  get button() { return this.btn("primary"); },
  get ghostButton() { return { ...this.btn("ghost"), marginTop: "8px" }; },
  label: {
    fontSize: "11px",
    color: "rgba(255,255,255,0.4)",
    letterSpacing: "1px",
    textTransform: "uppercase",
    fontWeight: "600",
    marginBottom: "6px",
    display: "block",
  },
  h1: { fontSize: "28px", fontWeight: "700", color: "#fff", lineHeight: "1.2", margin: 0 },
  h2: { fontSize: "20px", fontWeight: "700", color: "#fff", margin: 0 },
  h3: { fontSize: "16px", fontWeight: "600", color: "#fff", margin: 0 },
  get title() { return { fontSize: "26px", fontWeight: "800", color: "#fff", margin: 0, lineHeight: "1.2" }; },
  subtitle: { fontSize: "14px", color: "rgba(255,255,255,0.5)", lineHeight: "1.5", margin: "6px 0 0 0" },
  body: { fontSize: "14px", color: "rgba(255,255,255,0.55)", lineHeight: "1.5" },
  muted: { fontSize: "12px", color: "rgba(255,255,255,0.35)", margin: 0 },
  badge: (color = "#4ade80") => ({
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    padding: "4px 10px",
    borderRadius: "20px",
    fontSize: "11px",
    fontWeight: "600",
    background: color + "18",
    color: color,
    border: `1px solid ${color}30`,
  }),
  triggerBadge: (code) => {
    const c = TRIGGER_COLORS[code] || "#888";
    return {
      display: "inline-flex", alignItems: "center", gap: "4px",
      padding: "3px 8px", borderRadius: "6px", fontSize: "11px", fontWeight: "700",
      background: c + "20", color: c, border: `1px solid ${c}35`,
    };
  },
  statusPill: (status) => {
    const map = { SUCCESS: "#4ade80", success: "#4ade80", PENDING: "#f59e0b", pending: "#f59e0b", PASSIVE: "#6b7280", ACTIVE: "#4ade80", active: "#4ade80", "IN REVIEW": "#f59e0b", "IN PROGRESS": "#3b82f6", FAILED: "#ef4444", failed: "#ef4444" };
    const c = map[status] || "#888";
    return {
      display: "inline-flex", alignItems: "center", gap: "5px",
      padding: "3px 8px", borderRadius: "20px", fontSize: "10px", fontWeight: "600",
      background: c + "18", color: c, border: `1px solid ${c}30`,
    };
  },
  divider: { height: "1px", background: "rgba(255,255,255,0.06)", margin: "16px 0" },
  topBar: {
    display: "flex", alignItems: "center", justifyContent: "space-between",
    padding: "16px 20px 8px", position: "sticky", top: 0,
    background: "rgba(13,13,20,0.9)", backdropFilter: "blur(20px)", zIndex: 50,
  },
  bottomNav: {
    position: "fixed",
    bottom: 0,
    width: "390px",
    background: "rgba(13,13,20,0.95)",
    backdropFilter: "blur(20px)",
    borderTop: "1px solid rgba(255,255,255,0.06)",
    display: "flex",
    zIndex: 100,
    paddingBottom: "8px",
  },
  get tabBar() { return this.bottomNav; },
  navItem: (active) => ({
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    padding: "10px 0 4px",
    cursor: "pointer",
    color: active ? "#4ade80" : "rgba(255,255,255,0.35)",
    fontSize: "10px",
    fontWeight: "500",
    letterSpacing: "0.5px",
    textTransform: "uppercase",
    transition: "color 0.2s",
    userSelect: "none",
    background: "none",
    border: "none",
    fontFamily: "inherit",
  }),
  tabButton: (active) => ({
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
    padding: "10px 0 4px",
    cursor: "pointer",
    color: active ? "#4ade80" : "rgba(255,255,255,0.35)",
    fontSize: "10px",
    fontWeight: "500",
    letterSpacing: "0.5px",
    textTransform: "uppercase",
    transition: "color 0.2s",
    userSelect: "none",
    background: "none",
    border: "none",
    fontFamily: "inherit",
  }),
};
